---
  root: true
  parser: babel-eslint
  parserOptions:
    allowImportExportEverywhere: true
  extends: airbnb
  rules:
    import/order:
      - error
      - groups:
          - builtin
          - external
          - internal
          - parent
          - sibling
          - index
        newlines-between: always
